### ISSUE TITLE
How to start both locally

### ISSUE THREAD

**Issue by adityaChauhan2510** [Arunshaik2001/Paymnt-Transfer-karo#4]
Hey, I would like to contribute, can you tell me how to start both locally using docker-compose. Do I need to start them separately or run a single command?

**Comment by Arunshaik2001** [comment]
Hey @adityaChauhan2510 , thank you for taking out time.
just type in cmd
npm run docker-compose with env file.

you have to run this in both projects.

**Comment by adityaChauhan2510** [comment]
Also there are lot of env files. which all I need to specify. Just tell the whole process of running the application

**Comment by Arunshaik2001** [comment]
@adityaChauhan2510 this is my **env.js** file contents which i use to run locally as i am using pm2(because docker takes more memory and size) and then follow the readme to run.

this **env.js** file is in root folder where you have kept both paymnt and netbanking app.


const netbankConfig = {
    DATABASE_URL: "postgres://YOUR_DATABASE_URL/netbanking?sslmode=require",
    HDFC_JWT_LOGIN_SECRET: "PAYMNT_SECRET_HDFC",
    REDIS_URL: "YOUR_REDIS_URL"
}

const paymntConfig = {
    DATABASE_URL: "postgres://YOUR_DATABASE_URL/paymnt?sslmode=require",
    HDFC_PAYMNT_BANK_SERVER_KEY: "HDFC_SECRET",
    PAYMNT_HDFC_BANK_SERVER_KEY: "PAYMNT_SECRET_HDFC",
    KOTAK_PAYMNT_BANK_SERVER_KEY: "KOTAK_SECRET",
    PAYMNT_KOTAK_BANK_SERVER_KEY: "PAYMNT_SECRET_KOTAK",
    HDFC_BANK_SERVER: "http://localhost:4000",
    PAYMNT_WEBHOOK_PORT: 3005,
    PAYMNT_WEBSOCKET_PORT: 3006
}

module.exports = {
    netbankConfig,
    paymntConfig
};

I am using [aiven](https://aiven.io/) for database and redis. You can also get it for free from there.

I Hope this helps you

**Comment by Arunshaik2001** [comment]
@adityaChauhan2510 if you want to use docker

**npm run docker-compose**

but it will take more changes like endpoint changes to like renaming localhost to containerName

**Comment by adityaChauhan2510** [comment]
Thanks

**Comment by Arunshaik2001** [comment]
@adityaChauhan2510 Hey, I have made the changes to run the project locally using docker.

You can follow the readme of this branch to setup locally using docker

[Docker setup branch](https://github.com/Arunshaik2001/Paymnt-Transfer-karo/tree/docker-setup)

**Comment by Arunshaik2001** [comment]
Closing this issue
reopen if you have any issues setting up locally using docker or pm2

Thank You
